name = input("what is your name? ")
age = input("what is your age? ")
dateofbirth = input("what is your date of birth? ")
grade = input("what grade are you in? ")

print("--------------------------")
print(name)
print(age)
print(dateofbirth)
print(grade)